Alejandria/urls.py
from django.contrib import admin
from django.urls import path, include

from . import view
urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('', home, name='home'),
    # path('search', search),
    # path('book/<int:isbn>', showDetails),
    # path('cart/', cart, name='cart'),
    path('admin/', admin.site.urls),
    path('', include('books.urls')),

]

books/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'books'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('book/<slug:pk>/', views.BookView.as_view(), name='book'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('delete/<book>/', views.delete_product, name='delete_product'),
    path('add/<view>/<book>/', views.add_product, name='add_product'),
    path('faqs/', views.FaqsView.as_view(), name='faqs'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('sell/', views.SellView.as_view(), name='sell'),
    path('forgot/', views.forgot, name='forgot'),
    path('forgot/<id>/', views.forgot, name='reset'),
    path('review/<slug:pk>/', views.BookView.as_view(), name='post_review'),
    path('review/', views.leave_review, name='leave_review'),
    path('editor/', views.EditorLibrary.as_view(), name='editor_library'),
    path('profile/', views.view_profile, name="view_profile"),
    path('purchase/', views.complete_purchase, name='purchase'),
    path('editBook/<slug:pk>/', views.EditBookView.as_view(), name='edit_book'),
    path('deleteBook/<slug:pk>/', views.DeleteBookView.as_view(), name='delete_book'),
    path('pdf/', views.generate_pdf, name='generate_bill'),
    path('library/', views.UserLibrary.as_view(), name='user_library'),
    path('bills/', views.UserBills.as_view(), name='user_bills'),
    path('check/', views.check_data, name="check_username"),
    path('addfaq/', views.addfaq, name="add_faq"),
    path('modifyfaq/', views.modifyfaq, name="modify_faq"),
    path('deletefaq/', views.deletefaq, name="delete_faq"),
    path('desiredLibrary/', views.DesiredLibrary.as_view(), name='desired_library'),
#    path('download/', views.book_pdf, name="download_book"), TODO:CAN BE REMOVED IF WONT BE USED TO HAVE SAFER DOWNLOADS
    path('avatar/', views.post_avatar, name="avatar"),
    path('promocode/<code>', views.check_promo_code, name='check_promo_code'),
    path('checkUsernameGift/<username>', views.checkUsernameGift, name='check_username_gift'),
    path('about/', views.about_us, name='about_us')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.

"""
IF NECESSARY INTRODUCE help_text in some characteristics.
"""
GENRE_CHOICES = [
    ('FANT', 'Fantasy'),
    ('CRIM', 'Crime & Thriller'),
    ('FICT', 'Fiction'),
    ('SCFI', 'Science Fiction'),
    ('HORR', 'Horror'),
    ('ROMA', 'Romance'),
    ('TEEN', 'Teen & Young Adult'),
    ('KIDS', "Children's Books"),
    ('ANIM', 'Anime & Manga'),
    ('OTHR', 'Others'),
    ('ARTS', 'Art'),
    ('BIOG', 'Biography'),
    ('FOOD', 'Food'),
    ('HIST', 'History'),
    ('DICT', 'Dictionary'),
    ('HEAL', 'Health'),
    ('HUMO', 'Humor'),
    ('SPOR', 'Sport'),
    ('TRAV', 'Travel'),
    ('POET', 'Poetry')
]


class Address(models.Model):
    street = models.CharField(max_length=50, null=False, blank=False)
    city = models.CharField(validators=[RegexValidator(regex=r"^[A-Z][a-z]+$", message='Invalid city name.',
                                                       code='nomatch')], max_length=50, null=False, blank=False)
    country = models.CharField(validators=[RegexValidator(regex=r"^[A-Z][a-z]+$", message='Invalid country name.',
                                                          code='nomatch')], max_length=50, null=False, blank=False)
    zip = models.CharField(validators=[RegexValidator(regex=r"^[0-9]{4-7}$", message='Invalid zip. Must have 5 digits.',
                                                      code='nomatch')], max_length=10, null=False, blank=False)


class User(AbstractUser):
    id = models.AutoField(primary_key=True, null=False, blank=True)
    # TODO: ADD USERNAME AS A PK
    role = models.CharField(max_length=10, null=False, blank=False)
    name = models.CharField(validators=[RegexValidator(regex=r"^[A-Z][a-z ,.'-]+$", message='Invalid name.',
                                                       code='nomatch')], max_length=150, null=False, blank=False, default="user")
    password = models.CharField(validators=[RegexValidator(regex=r"^[A-Za-z0-9]{6,20}$", message='Invalid password.',
                                                           code='nomatch')], max_length=150, null=False, blank=False)
    email = models.EmailField(validators=[RegexValidator(regex=r"^[A-Za-z0-9](\.?[A-Za-z0-9]){5,}@g(oogle)?mail\.com$", message='Invalid email.',
                                                         code='nomatch')], max_length=150, null=False, blank=False)
    user_address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True, null=True,
                                     related_name="user_address")
    fact_address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True, null=True,
                                     related_name="fact_address")
    genre_preference_1 = models.CharField(max_length=4, choices=GENRE_CHOICES, blank=True, null=True)
    genre_preference_2 = models.CharField(max_length=4, choices=GENRE_CHOICES, null=True, blank=True)
    genre_preference_3 = models.CharField(max_length=4, choices=GENRE_CHOICES, null=True, blank=True)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatars/")


class Guest(models.Model):
    id = models.AutoField(primary_key=True, null=False, blank=True)
    device = models.CharField(max_length=200, null=False, blank=False)


# class Author(models.Model):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#
#     def __eq__(self, other):
#         if isinstance(other, self.__class__):
#             return self.__dict__ == other.__dict__
#         else:
#             return False


class Book(models.Model):
    ISBN = models.CharField(primary_key=True, max_length=13, blank=False, null=False)  # Its a Char instead of Integer
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(max_length=1000, blank=True, null=True)  # Synopsis
    saga = models.CharField(max_length=100, blank=True, null=True)
    # authors = models.ManyToManyField(Author, max_length=10, blank=True, null=True,
    #                                  default=None)  # Un llibre pot tenir més d'un autor.
    author = models.CharField(max_length=50, default="Anonymous")
    # Has to be datetime.date
    # By default it's now.
    publication_date = models.DateField(null=True, blank=True, default=timezone.now)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    language = models.CharField(max_length=30, blank=False)
    primary_genre = models.CharField(max_length=4, choices=GENRE_CHOICES, default='OTHR')
    secondary_genre = models.CharField(max_length=4, choices=GENRE_CHOICES, null=True, blank=True)
    publisher = models.CharField(max_length=50)
    num_pages = models.IntegerField(blank=False)
    num_sold = models.IntegerField(default=0)
    recommended_age = models.CharField(max_length=30, blank=True,
                                       null=True)
    # Path to thumbnail(Thubnail identified by ISBN)
    thumbnail = models.ImageField(blank=True, null=True, upload_to="thumbnails/")  # TODO:Should be blank=False in the Future
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=0, blank=True, null=True)
    eBook = models.FileField(blank=True, null=True, upload_to="ebooks/", default="/media/ebooks/download.pdf")
    # pub_date = publication_date  # Abreviation


class BookProperties(models.Model):
    id = models.AutoField(primary_key=True, blank=False, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False,
                             blank=False)
    desired = models.BooleanField(default=False)
    readed = models.BooleanField(default=False)


class Rating(models.Model):
    ID = models.AutoField(primary_key=True, blank=False, null=False)
    ISBN = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, blank=False)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False,
                                blank=False)
    text = models.TextField(max_length=500, null=False, blank=True)
    per_values = range(1, 6)
    human_readable = [str(value) for value in per_values]
    score = models.IntegerField(choices=zip(per_values, human_readable), null=False, blank=False)
    date = models.DateField(null=True, blank=True, default=timezone.now)


class Cupon(models.Model):
    code = models.CharField(primary_key=True, max_length=10, blank=False, null=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False, blank=False)
    percentage = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], null=False)
    max_limit = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(99999999)], null=True)
    redeemed = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(99999999)], null=True, default=0)


class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    guest_id = models.ForeignKey(Guest, on_delete=models.CASCADE, blank=False, null=True)
    books = models.ManyToManyField(Book)


class Bill(models.Model):
    num_bill = models.AutoField(primary_key=True, blank=False, null=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date = models.DateField(null=True, blank=True, default=timezone.now)
    payment_method = models.CharField(max_length=50)
    books = models.ManyToManyField(Book)
    total_money_spent = models.DecimalField(decimal_places=2, max_digits=8, null=True)


class LibraryBills(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=False)
    bills = models.ManyToManyField(Bill)


class FAQ(models.Model):
    # First object = Saved on the model, second object = Human readable one
    FAQ_CHOICES = [
        ('DWL', 'About our ebooks'),
        ('REF', 'Refund'),
        ('SEL', 'Sell your ebooks'),
        ('FAC', 'About bills and payment'),
        ('CON', 'Contact us'),
    ]

    ID = models.AutoField(primary_key=True)

    question = models.TextField(blank=False, null=False)
    answer = models.TextField(blank=False, null=False)
    category = models.CharField(blank=False, null=False, choices=FAQ_CHOICES, max_length=50)

    def __str__(self):
        return "ID:{}  CAT:{}   {} --- {}".format(self.ID, self.category, self.question, self.answer)


## TODO: If we decide to give the option to the admin to add the FAQ to a new category, categories shold be saved to the database
# class FAQchoices(models.Model):


class ResetMails(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False, blank=False)
    activated = models.BooleanField(default=True)


class BankAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    name = models.CharField(max_length=100)
    money = models.DecimalField(decimal_places=2, max_digits=8, default=500.00)
    card_number = models.CharField(validators=[RegexValidator(regex=r'^[0-9]{16}$', message='Length has to be 16',
                                                              code='nomatch')], max_length=16, null=True)
    month_exp = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)], null=True)
    year_exp = models.IntegerField(validators=[MinValueValidator(2020)], null=True)
    cvv = models.IntegerField(validators=[MinValueValidator(000), MaxValueValidator(9999)], null=True)  # 3 or 4 digits

Alejandria/templates/desired_library.html
<!DOCTYPE html>

{% extends "navbar.html" %}
{% load static %}

{% block content %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Alejandria</title>

    <link rel="stylesheet" href="{% static 'css/editor-page/card.css' %}">
    {% if desired_books|length == 0 %}
    <link rel="stylesheet" href="{% static 'css/navbar-page/footer2.css' %}">
    {% endif %}
</head>

<body>

<div class="container-fluid" style="margin-bottom: 5%;">
    {% for book,price in desired_books %}
    <div class="row border-colored" style="background-color: #963434; margin-left: 15%; margin-right:15%; margin-top:2%;">

        <div class="col-2" style="padding: 0">
            {% if book.discount != 0 %}
            <div class="tag">ON SALE!</div>
            {% endif %}
            {% if book.thumbnail %}
            <img src="{{ book.thumbnail.url }}" alt="Card image cap" style="width:100%">
            {% else %}
            <img src="{% static 'no_available.jpg' %}" alt="Card image cap" style="width:100%">
            {% endif %}
        </div>

        <div class="col-1"></div>

        {% if book.discount != 0 %}
        <div class="col-9 vertical-center">
        {% else %}
        <div class="col-9">
        {% endif %}
            <h3 style="font-size:24px; color:white">{{ book.title }}</h3>
            <div class="row" style="margin-top:2%;">
                <div class="col">
                    <h6 style="font-size:16px; color:white"><b>Author:</b> {{ book.author }} </h6>
                    <h6 style="font-size:16px; color:white"><b>Saga:</b> {{ book.saga }} </h6>
                    <h6 style="font-size:16px; color:white"><b>Genre:</b> {{ book.get_primary_genre_display }}, {{ book.get_secondary_genre_display }}</h6>
                    {% if book.discount != 0 %}
                    <h6 style="font-size:16px; color:white">Price:
                        <del>{{book.price}}€</del>
                    </h6>
                    <h6 style="font-size:16px; color:white"><b>Discount: {{book.discount}}%!</b></h6>
                    <h6 style="font-size:16px; color:white">New price: {{ price }}€ </h6>
                    {% else %}
                    <h6 style="font-size:16px; color:white">Price: {{book.price}}€</h6>
                    {% endif %}
                    <h6 style="font-size:16px; color:white"><b>Publication date:</b> {{ book.publication_date }} </h6>
                </div>
                <div class="col">
                    <h6 style="font-size:16px; color:white"><b>ISBN:</b> {{ book.ISBN }}</h6>
                    <h6 style="font-size:16px; color:white"><b>Language:</b> {{ book.language }} </h6>
                    <br>
                    <div class="row">
                        <div class="col-2">
                            <form action="/book/{{book.ISBN}}">
                                <button class="btn btn-danger my-2 my-sm-0 border-colored" style="width:40px; height: 40px" title="Show" type="submit"><i
                                        class="fas fa-search"></i></button>
                            </form>
                        </div>
                        <div class="col-2">
                            <a href="{% url 'books:add_product' 'home' book.ISBN %}" style="width:40px; height: 40px"
                               class="btn btn-danger my-2 my-sm-0 border-colored">
                                <i class="fas fa-shopping-cart"></i>
                            </a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </div>
    {% endfor %}

    {% if desired_books|length == 0 %}
    <div class="col-12 mt-3" style="color: white; text-align: center;">
        <h3>Seems like you did not add any desired book yet...</h3>
    </div>
    {% endif %}

</div>
</body>
{% endblock %}
</html>

Alejandria/templates/editor_library.html
<!DOCTYPE html>

{% extends "navbar.html" %}
{% load static %}

{% block content %}

<html lang="en">

<link rel="stylesheet" href="{% static 'css/editor-page/card.css' %}">
<head>
    <meta charset="UTF-8">
    <title>Alejandria</title>
</head>
<body>
{% if messages %}
  {% for msg in messages %}
    <div class="alert alert-info alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{msg.message}}
    </div>
  {% endfor %}
{% endif %}
    <div class="container-fluid">
        <div class="row" >
            <div class="col-12 mt-3"  >
                {% for book in editor_books %}

                    <div class="card" style="background-color: #963434; margin-left: 15%; margin-right:15%; margin-top:2%;">
                         <div class="card-horizontal" >
                             {% if book.thumbnail %}
                                <img src="{{ book.thumbnail.url }}" alt="Card image cap" style="width:180px; height:250px;">
                                {% else %}
                                <img src= "{% static 'no_available.jpg' %}" alt="Card image cap" style="width:180px; height:250px;">
                            {% endif %}
                             <div class="card-body" style="color:white;" >
                                 <h3 class="card-title">{{ book.title }}</h3>
                                 <div class="row" style="margin-top:2%;">
                                     <div class="column" style="margin-left:5%;" >
                                         <h6 class="card-title"><b>Author:</b> {{ book.author }} </h6>
                                         <h6 class="card-title"><b>Saga:</b> {{ book.saga }} </h6>
                                         <h6 class="card-title"><b>Price:</b> {{ book.price }} €</h6>
                                         <h6 class="card-title"><b>Num sold:</b> {{ book.num_sold }} </h6>
                                     </div>
                                     <div class="column" style="position: absolute; right: 30%">
                                         <h6 class="card-title"><b>ISBN:</b> {{ book.ISBN }}</h6>
                                         <h6 class="card-title"><b>Genre:</b> {{ book.get_primary_genre_display }}, {{ book.get_secondary_genre_display }}</h6>
                                         <h6 class="card-title"><b>Language:</b> {{ book.language }} </h6>
                                         <h6 class="card-title"><b>Publication date:</b> {{ book.publication_date }} </h6>
                                     </div>
                                     <div class="column" style="position: absolute; right: 5%; " >
                                        <div clas="row" style="margin-top: 5%;">
                                            <form action="/book/{{book.ISBN}}">
                                                <button class="btn btn-danger my-2 my-sm-0"  style="width:100%" title="Show"  type="submit"><i class="fas fa-search"></i></button>
                                            </form>
                                          </div>
                                         <div clas="row" style="margin-top:5%;">
                                             <form action="/editBook/{{book.ISBN}}">
                                                <button class="btn btn-danger my-2 my-sm-0" style="width:100%" title="Edit" type="submit"><i class="fas fa-edit"></i></button>
                                             </form>
                                          </div>
                                         <div clas="row" style="margin-top: 5%;" >
                                             <form action="/deleteBook/{{book.ISBN}}">
                                                <button class="btn btn-danger my-2 my-sm-0" style="width:100%" title="Delete" type="submit"><i class="fas fa-trash-alt"></i></button>
                                             </form>
                                         </div>
                                     </div>
                                 </div>

                            </div>
                        </div>
                    </div>
                        {% endfor %}
                <a style="text-decoration: none;" href="/sell">
                <div class="card-add" style="background-color: #963434; margin-left: 15%; margin-right:15%; margin-top:2%; margin-bottom: 5%">
                         <div class="card-horizontal" >

                             <div class="card-body" style="color:white;" >
                                 <h3 class="card-title" style="text-align:center">Add new book</h3>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</body>
</html>


{% endblock %}

Alejandria/templates/not_found.html
<!DOCTYPE html>

{% extends "navbar.html" %}
{% load static %}

{% block content %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alejandria</title>




    <link rel="stylesheet" href="{% static 'css/buttons2.css' %}">
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/404.scss' %}">
    <script src="//cdn.jsdelivr.net/npm/less" ></script>
    <script type="text/javascript" src="{% static 'js/404.js' %}"></script>


</head>
<body>
    <div class="container">
  <div class="copy-container center-xy">
    <p>
      404, page not found.
    </p>
    <span class="handle"></span>

  </div>
</div>

    <script>
    $(document).ready(function () {
        Swal.fire({
            icon: 'error',
            title: 'Error 404',
            text: 'Not found',
        })
    })
</script>

<svg version="1.1" id="cb-replay" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 279.9 297.3" style="enable-background:new 0 0 279.9 297.3;" xml:space="preserve">
<g>
	<path d="M269.4,162.6c-2.7,66.5-55.6,120.1-121.8,123.9c-77,4.4-141.3-60-136.8-136.9C14.7,81.7,71,27.8,140,27.8
		c1.8,0,3.5,0,5.3,0.1c0.3,0,0.5,0.2,0.5,0.5v15c0,1.5,1.6,2.4,2.9,1.7l35.9-20.7c1.3-0.7,1.3-2.6,0-3.3L148.6,0.3
		c-1.3-0.7-2.9,0.2-2.9,1.7v15c0,0.3-0.2,0.5-0.5,0.5c-1.7-0.1-3.5-0.1-5.2-0.1C63.3,17.3,1,78.9,0,155.4
		C-1,233.8,63.4,298.3,141.9,297.3c74.6-1,135.1-60.2,138-134.3c0.1-3-2.3-5.4-5.3-5.4l0,0C271.8,157.6,269.5,159.8,269.4,162.6z"/>
</g>
</svg>

</body>
{% endblock %}
</html>

Alejandria/templates/view_profile.html
<!DOCTYPE html>
{% extends "navbar.html" %}
{% load static %}

{% block content %}

<html lang="en">
</html>
<head>
  <meta charset="UTF-8">

    <script type="text/javascript" src="{% static 'js/profile.js' %}"></script>
    {% csrf_token %}
</head>
<body>

<div class="container">
    <div class="main-body" style="margin-top: 15%">

          <!-- /Breadcrumb -->

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card" id="mainCard">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" id="avatar-2" class="rounded-circle" width="150" height="150">
                    {% else %}
                    <img src="https://www.computerhope.com/jargon/g/guest-user.jpg" id="avatar-2" class="rounded-circle" width="150" height="150">
                    {% endif %}
                    <input id="avatar-field" name="avatar" class="d-none" type="file" required>
                    <div class="mt-3">
                      <h4>{{ user.username }}</h4>
                      <p class="text-secondary mb-1">{{ user.name }}</p>
                      <p class="text-muted font-size-sm">{{ user.user_address.city }} , {{ user.user_address.zip }}</p>
                      <button class="btn btn-danger" id="edit_btn">Edit Profile</button>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div class="col-md-8">
              <div class="card mb-3" id="profile">
                  <center style="margin-top: 2%">
                      <h5 class="card-title">Profile</h5>
                  </center>
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Username</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_username">
                      {{ user.username }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_name">
                      {{ user.name }} {{ user.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_email">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Street</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_street1">
                      {{ user.user_address.street }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">City</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_city1">
                      {{ user.user_address.city }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Country</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_country1">
                      {{ user.user_address.country }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Zip Code</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_zip1">
                      {{ user.user_address.zip }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card" id="tastes">
              <center style="margin-top: 2%">
                  <h5 class="card-title">Tastes</h5>
              </center>
                <div class="card-body" style="margin-top: 2%;">
                      <div class="row">
                        <div class="col-sm-4">
                          <h6 class="mb-0">Taste 1</h6>
                        </div>
                        <div class="col-sm-6 text-secondary" id="id_taste1">
                          {{ user.get_genre_preference_1_display }}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-4">
                          <h6 class="mb-0">Taste 2</h6>
                        </div>
                        <div class="col-sm-6 text-secondary" id="id_taste2">
                          {{ user.get_genre_preference_2_display }}
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-4">
                          <h6 class="mb-0">Taste 3</h6>
                        </div>
                        <div class="col-sm-6 text-secondary" id="id_taste3">
                          {{ user.get_genre_preference_3_display }}
                        </div>
                      </div>

                </div>
              </div>
            </div>


            <div class="col-md-8">
              <div class="card mb-3" id="facturation">
                  <center style="margin-top: 2%">
                      <h5 class="card-title">Facturation</h5>
                  </center>

                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Street</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_street2">
                      {{ user.fact_address.street }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">City</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_city2">
                      {{ user.fact_address.city }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Country</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_country2">
                      {{ user.fact_address.country }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Zip Code</h6>
                    </div>
                    <div class="col-sm-9 text-secondary" id="id_zip2">
                      {{ user.fact_address.zip }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

</body>
{% endblock %}